baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yiran Guo'
theme = "huey"

[menu]

# Top Navigation

[[menu.nav]]
  identifier = 'moving-image'
  name = 'Moving Image'
  title = "Moving Image"
  hasChildren = true
  weight = 20
  
[[menu.nav]]
  identifier = 'xiang'
  name = 'Xiang'
  title = "Xiang"
  parent = "moving-image"
  url = '/moving-image/xiang/'
  hasChildren = false
  weight = 20
  
[[menu.nav]]
  identifier = 'composition-of-air'
  name = 'Composition of Air'
  title = "Composition of Air"
  parent = "moving-image"
  url = '/moving-image/composition-of-air/'
  hasChildren = false
  weight = 20
  
[[menu.nav]]
  identifier = 'live-visuals'
  name = 'Live Visuals'
  title = "Live Visuals"
  parent = "moving-image"
  url = '/moving-image/live-visuals/'
  hasChildren = false
  weight = 20
  
[[menu.nav]]
  identifier = 'works-on-paper'
  name = 'Works on Paper'
  title = "Works on Paper"
  hasChildren = true
  weight = 20
  
[[menu.nav]]
  identifier = 'xiang-prints'
  name = 'Xiang Prints'
  title = "Xiang Prints"
  parent = "works-on-paper"
  url = '/works-on-paper/xiang-prints/'
  hasChildren = false
  weight = 20
  
[[menu.nav]]
  identifier = 'eggs'
  name = 'Eggs'
  title = "Eggs"
  parent = "works-on-paper"
  url = '/works-on-paper/eggs/'
  hasChildren = false
  weight = 20
  
[[menu.nav]]
  identifier = 'soft-landing'
  name = 'Soft Landing'
  title = "Soft Landing"
  parent = "works-on-paper"
  url = '/works-on-paper/soft-landing/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'recycle'
  name = 'Recycle'
  title = "Recycle"
  parent = "works-on-paper"
  url = '/works-on-paper/recycle/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'pox'
  name = 'Pox'
  title = "Pox"
  parent = "works-on-paper"
  url = '/works-on-paper/pox/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'under-the-banana-leaves-a-man'
  name = 'Under the Banana Leaves, A Man'
  title = "Under the Banana Leaves, A Man"
  parent = "works-on-paper"
  url = '/works-on-paper/under-the-banana-leaves-a-man/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'monkey'
  name = 'Monkey'
  title = "Monkey"
  parent = "works-on-paper"
  url = '/works-on-paper/monkey/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'smells'
  name = 'Smells'
  title = "Smells"
  parent = "works-on-paper"
  url = '/works-on-paper/smells/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'recycle'
  name = 'Recycle'
  title = "Recycle"
  parent = "works-on-paper"
  url = '/works-on-paper/recycle/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'mono-prints'
  name = 'Mono Prints'
  title = "Mono Prints"
  parent = "works-on-paper"
  url = '/works-on-paper/mono-prints/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'gaze'
  name = 'Gaze'
  title = "Gaze"
  parent = "works-on-paper"
  url = '/works-on-paper/gaze/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'faces-in-my-studio'
  name = 'Faces in My Studio'
  title = "Faces in My Studio"
  parent = "works-on-paper"
  url = '/works-on-paper/faces-in-my-studio/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'butter-fly'
  name = 'Butter Fly'
  title = "Butter Fly"
  parent = "works-on-paper"
  url = '/works-on-paper/butter-fly/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'books'
  name = 'Books'
  title = "Books"
  parent = "works-on-paper"
  url = '/works-on-paper/books/'
  hasChildren = false
  weight = 20

[[menu.nav]]
  identifier = 'objects'
  name = 'Objects'
  title = "Objects"
  hasChildren = true
  weight = 20

[[menu.nav]]
  identifier = 'Ceramics'
  name = 'Ceramics'
  title = "Ceramics"
  parent = "objects"
  url = '/objects/ceramics/'
  hasChildren = false
  weight = 20
  
[[menu.nav]]
  identifier = 'Fabric'
  name = 'Fabric'
  title = "Fabric"
  parent = "objects"
  url = '/objects/fabric/'
  hasChildren = false
  weight = 20